//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Banana.DBModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class BananaContext : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“BananaContext”部分中的连接字符串初始化新 BananaContext 对象。
        /// </summary>
        public BananaContext() : base("name=BananaContext", "BananaContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BananaContext 对象。
        /// </summary>
        public BananaContext(string connectionString) : base(connectionString, "BananaContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BananaContext 对象。
        /// </summary>
        public BananaContext(EntityConnection connection) : base(connection, "BananaContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Ba_UserInfo> Ba_UserInfo
        {
            get
            {
                if ((_Ba_UserInfo == null))
                {
                    _Ba_UserInfo = base.CreateObjectSet<Ba_UserInfo>("Ba_UserInfo");
                }
                return _Ba_UserInfo;
            }
        }
        private ObjectSet<Ba_UserInfo> _Ba_UserInfo;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Ba_UserInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBa_UserInfo(Ba_UserInfo ba_UserInfo)
        {
            base.AddObject("Ba_UserInfo", ba_UserInfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BananaModel", Name="Ba_UserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ba_UserInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Ba_UserInfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Ba_UserInfo CreateBa_UserInfo(global::System.String id)
        {
            Ba_UserInfo ba_UserInfo = new Ba_UserInfo();
            ba_UserInfo.Id = id;
            return ba_UserInfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, true, "LoginName");
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealName
        {
            get
            {
                return _RealName;
            }
            set
            {
                OnRealNameChanging(value);
                ReportPropertyChanging("RealName");
                _RealName = StructuralObject.SetValidValue(value, true, "RealName");
                ReportPropertyChanged("RealName");
                OnRealNameChanged();
            }
        }
        private global::System.String _RealName;
        partial void OnRealNameChanging(global::System.String value);
        partial void OnRealNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserIcon
        {
            get
            {
                return _UserIcon;
            }
            set
            {
                OnUserIconChanging(value);
                ReportPropertyChanging("UserIcon");
                _UserIcon = StructuralObject.SetValidValue(value, true, "UserIcon");
                ReportPropertyChanged("UserIcon");
                OnUserIconChanged();
            }
        }
        private global::System.String _UserIcon;
        partial void OnUserIconChanging(global::System.String value);
        partial void OnUserIconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value, "CreateDate");
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDel
        {
            get
            {
                return _IsDel;
            }
            set
            {
                OnIsDelChanging(value);
                ReportPropertyChanging("IsDel");
                _IsDel = StructuralObject.SetValidValue(value, "IsDel");
                ReportPropertyChanged("IsDel");
                OnIsDelChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDel;
        partial void OnIsDelChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDelChanged();

        #endregion

    }

    #endregion

}
