//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Banana.DBModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class BaWeixinEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“BaWeixinEntities”部分中的连接字符串初始化新 BaWeixinEntities 对象。
        /// </summary>
        public BaWeixinEntities() : base("name=BaWeixinEntities", "BaWeixinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BaWeixinEntities 对象。
        /// </summary>
        public BaWeixinEntities(string connectionString) : base(connectionString, "BaWeixinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BaWeixinEntities 对象。
        /// </summary>
        public BaWeixinEntities(EntityConnection connection) : base(connection, "BaWeixinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Ba_Subscribe> Ba_Subscribe
        {
            get
            {
                if ((_Ba_Subscribe == null))
                {
                    _Ba_Subscribe = base.CreateObjectSet<Ba_Subscribe>("Ba_Subscribe");
                }
                return _Ba_Subscribe;
            }
        }
        private ObjectSet<Ba_Subscribe> _Ba_Subscribe;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Ba_Food> Ba_Food
        {
            get
            {
                if ((_Ba_Food == null))
                {
                    _Ba_Food = base.CreateObjectSet<Ba_Food>("Ba_Food");
                }
                return _Ba_Food;
            }
        }
        private ObjectSet<Ba_Food> _Ba_Food;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Ba_Subscribe EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBa_Subscribe(Ba_Subscribe ba_Subscribe)
        {
            base.AddObject("Ba_Subscribe", ba_Subscribe);
        }
    
        /// <summary>
        /// 用于向 Ba_Food EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBa_Food(Ba_Food ba_Food)
        {
            base.AddObject("Ba_Food", ba_Food);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaWeixinModel", Name="Ba_Food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ba_Food : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Ba_Food 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Ba_Food CreateBa_Food(global::System.String id)
        {
            Ba_Food ba_Food = new Ba_Food();
            ba_Food.ID = id;
            return ba_Food;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FoodName
        {
            get
            {
                return _FoodName;
            }
            set
            {
                OnFoodNameChanging(value);
                ReportPropertyChanging("FoodName");
                _FoodName = StructuralObject.SetValidValue(value, true, "FoodName");
                ReportPropertyChanged("FoodName");
                OnFoodNameChanged();
            }
        }
        private global::System.String _FoodName;
        partial void OnFoodNameChanging(global::System.String value);
        partial void OnFoodNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic
        {
            get
            {
                return _Pic;
            }
            set
            {
                OnPicChanging(value);
                ReportPropertyChanging("Pic");
                _Pic = StructuralObject.SetValidValue(value, true, "Pic");
                ReportPropertyChanged("Pic");
                OnPicChanged();
            }
        }
        private global::System.String _Pic;
        partial void OnPicChanging(global::System.String value);
        partial void OnPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value, "CreateDate");
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaWeixinModel", Name="Ba_Subscribe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ba_Subscribe : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Ba_Subscribe 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Ba_Subscribe CreateBa_Subscribe(global::System.String id)
        {
            Ba_Subscribe ba_Subscribe = new Ba_Subscribe();
            ba_Subscribe.ID = id;
            return ba_Subscribe;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromUserName
        {
            get
            {
                return _FromUserName;
            }
            set
            {
                OnFromUserNameChanging(value);
                ReportPropertyChanging("FromUserName");
                _FromUserName = StructuralObject.SetValidValue(value, true, "FromUserName");
                ReportPropertyChanged("FromUserName");
                OnFromUserNameChanged();
            }
        }
        private global::System.String _FromUserName;
        partial void OnFromUserNameChanging(global::System.String value);
        partial void OnFromUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OptionDate
        {
            get
            {
                return _OptionDate;
            }
            set
            {
                OnOptionDateChanging(value);
                ReportPropertyChanging("OptionDate");
                _OptionDate = StructuralObject.SetValidValue(value, "OptionDate");
                ReportPropertyChanged("OptionDate");
                OnOptionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OptionDate;
        partial void OnOptionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOptionDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    }

    #endregion

}
